server:
  port: 8090

spring:
  application:
    name: auth-server
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: gallery-admin
      password: pass
    realmImportFile: gallery-realm.json

eureka:
  client:
    service-url:
      defaultZone: http://servicediscovery:8761/eureka
  instance:
    hostname: servicediscovery
    prefer-ip-address: true
